name: Deploy Docker App to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ssh에 접속하여 script 실행
    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            cd /home/ubuntu/server
