name: Deploy to Ubuntu Docker Server

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시 시 동작

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: 22
        script: |
          cd /path/to/your/docker-project
          git pull origin main
          docker-compose down
          docker-compose up -d --build
